module.exports = {
    build: require('./build'),
    cards: require('./cards'),
    deck: require('./deck').deck,
    deckSheet: require('./deckSheet'),
    errata: require('./errata'),
    et: require('./et'),
    faq: require('./faq'),
    help: require('./help'),
    invite: require('./invite'),
    manualDeckSheet: require('./manualDeckSheet'),
    multiDeck: require('./multiDeck'),
    patreon: require('./patreon'),
    poly: require('./poly'),
    randomCard: require('./randomCard'),
    randomHand: require('./randomHand'),
    restart: require('./restart'),
    rule: require('./rule'),
    sealed: require('./sealed'),
    spoiler: require('./spoiler'),
    stats: require('./stats'),
    text: require('./text'),
    timingChart: require('./timingChart'),
    trait: require('./trait'),
    version: require('./version'),
    weirdo: require('./weirdo'),
    shardstatus: require('./admin').shardStatus
};
